name: Release
run-name: ${{ github.actor }} is building new release ${{ github.ref_name }} 🚀

on:
  push:
    tags:
      - "v*.*.*"

env:
  NC_APP_NAME: cfg_share_links
  SIGNATURE_NAME: release_signature.base64

jobs:
  prepare-new-version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    name: Update changelog and app version
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r .github/release/requirements.txt
      - run: python .github/release/prepare_release.py ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit changes and update tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add appinfo/info.xml CHANGELOG.md
          git commit -m "Bump version: ${{ github.ref_name }}"
          git push
          git tag -f ${{ github.ref_name }}
          git push origin -f --tags

      - name: Upload info.xml and changelog
        uses: actions/upload-artifact@v4
        with:
          name: updated-files
          path: |
            appinfo/info.xml
            CHANGELOG.md

  node:
    needs: [prepare-new-version]
    runs-on: ubuntu-latest
    name: Build and upload node artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read node and npm versions from package.json
        uses: skjnldsv/read-package-engines-version-actions@v2
        id: node-engine-versions
        with:
          fallbackNode: '^20'
          fallbackNpm: '^10'

      - name: Set up node ${{ steps.node-engine-versions.outputs.nodeVersion }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-engine-versions.outputs.nodeVersion }}
          cache: 'npm'

      - name: Set up npm ${{ steps.node-engine-versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.node-engine-versions.outputs.npmVersion }}"

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build --if-present

      - name: Upload node artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-artifacts
          path: |
            js/
            img/

  php:
    needs: [prepare-new-version]
    runs-on: ubuntu-latest
    name: Get and upload PHP artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: curl

      - name: Run composer install
        run: composer install --prefer-dist

      - name: Upload PHP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-artifacts
          path: |
            appinfo/routes.php
            l10n/
            lib/
            templates/
            vendor/
            openapi.json

  upload-release-asset:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [node, php]
    runs-on: ubuntu-latest
    name: Sign and upload release asset
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.NC_APP_NAME }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            COPYING
            README.md

      - name: Download node and PHP artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.NC_APP_NAME }}
          merge-multiple: true

      - name: Create release tarball
        run: tar -czvf ${{ env.NC_APP_NAME }}.tar.gz --exclude-vcs ${{ env.NC_APP_NAME }}

      - name: Sign release tarball
        shell: bash
        run: |
          echo "$SIGNING_KEY" | base64 --decode > private.key
          openssl dgst -sha512 -sign private.key ${{ env.NC_APP_NAME }}.tar.gz | openssl base64 > ${{ env.SIGNATURE_NAME }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            ${{ env.NC_APP_NAME }}.tar.gz
            ${{ env.SIGNATURE_NAME }}
